
package com.cxins.cn.message.webserviceTest;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-08-19T11:22:34.927+08:00
 * Generated source version: 2.5.0
 * 
 */
public final class HelloWorldService_HelloWorldServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.message.cn.cxins.com/", "HelloWorldServiceService");

    private HelloWorldService_HelloWorldServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldServiceService ss = new HelloWorldServiceService(wsdlURL, SERVICE_NAME);
        HelloWorldService port = ss.getHelloWorldServicePort();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_arg0 = "";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_arg0);
        System.out.println("sayHello.result=" + _sayHello__return);


        }
        {
        System.out.println("Invoking beginWork...");
        java.lang.String _beginWork_arg0 = "";
        java.lang.String _beginWork__return = port.beginWork(_beginWork_arg0,_beginWork_arg0);
        System.out.println("beginWork.result=" + _beginWork__return);


        }

        System.exit(0);
    }

}
